### ISSUE TITLE
1.16.5 LegendControl doesn't work if pokeballs are thrown at the legendary pokemon

### ISSUE THREAD

**Issue by EibonGit** [VecooDEV/LegendControl#2]
You can just throw your masterball at the protected legendary and it will catch it anyways...
Am I doing something wrong??

**Comment by VecooDEV** [comment]
Hello. Pokeball protection is present. You need to catch Pokemon outside of creative mode. And also make sure that the protection for the Pokemon is turned on.

**Comment by EibonGit** [comment]
I guess thats a permission issue on my part then.

**Comment by VecooDEV** [comment]
Try updating the mod to the latest version and setting up the configuration as stated in the wiki.
